### ISSUE TITLE
Reserved Word "class" in compressed version (loadingoverlay.min.js)

### ISSUE THREAD

**Issue by shyangs** [gasparesganga/jquery-loading-overlay#29]
![loadingoverlay min js](https://user-images.githubusercontent.com/244384/39299321-07b2025e-497b-11e8-8a47-14b0d900039a.PNG)

should be `"class"`, not `class`

**Comment by gasparesganga** [comment]
The minified version is processed using [gulp-uglify](https://github.com/terinjokes/gulp-uglify) which in turn uses [UglifyJS](https://github.com/mishoo/UglifyJS2).
The only way to prevent this would be *(maybe, since I hanven't tested it)* using the `ie8` option to `true`, but I will have to look into it.

Again, I explicitly **do not** support ie8. Now, if changes are minimal and don't impact negatively the project on the whole, I am disposed to make them. But please **check if it works with IE8, since it is not supposed to, due to heavy flexbox use**. You can use the non-compressed version for this purpose.

**Comment by gasparesganga** [comment]
I'm sorry but it is not worth to change things just to support IE8 in the **minified** version.

The solution is as simple as I wrote last time: use the **un-minified version**, where all the *reserved word* are quoted.
