### ISSUE TITLE
"progressFixedPosition is not defined"

### ISSUE THREAD

**Issue by Ofer-Gal** [gasparesganga/jquery-loading-overlay#36]
When I use element.LoadingOverlay("show",{size:500,text:'Loading', progressFixedPosition:'top 400px'}); 
I get error "progressFixedPosition is not defined"
I can only attach it to an element in the begining of the page but I want it to show in the middle more or less.

**Comment by gasparesganga** [comment]
What version are you using? I'd love to help you but I can't reproduce that error.
Actually your code does not make sense if you don't set `progress` to `true` as well. 

Also, could you elaborate your last sentence? I'm sorry but I don't get it.

**Comment by Ofer-Gal** [comment]
I realized now that it is only for a progress bar that I do not use.
I have the code element.LoadingOverlay("show",{size:500,text:'Loading'}); and the element is a textbox that sits at top:187px. Everything below it is in the process of loading so I can't attach to it before loading.
So the spinner shows on the input box. 
I would like to show it, more or less, in the middle of the window. So I tried to add in my CSS 
.loadingoverlay{
    top: 400px; 
}
But that did not do it.
Is there another trick I can use to do it? CSS?  jQuery?
Thank you in advance

**Comment by Ofer-Gal** [comment]
Never mind.
```
.loadingoverlay, .loadingoverlay_text, .loadingoverlay_element  {
       top: 400px  !important;
}
```
Did the trick.  
Thank you anyway.

**Comment by gasparesganga** [comment]
Actually the plugin does exaxtly what you are asking for: *showing elements in the middle to the window/container*. The problem here is that your container's height is increasing while you are loading elements.
Usually, for these scenarios, it's much better and cleaner to use a whole page overlay, without attaching it to any spefici element: `$.LoadingOverlay("show");`

Anyways, coming back to your custom CSS, there's no need to overwrite default classes and use `!important` clauses, which are very ugly. Options `imageClass` and `textClass` come in handy and are thought exactly for that:
```css
.custom_class_image {
    position : absolute;
    top      : 400px;
}
.custom_class_text {
    position : absolute;
    top      : 200px;
}
```
```javascript
$(your_element).LoadingOverlay("show", {
    imageClass  : "custom_class_image",
    textClass   : "custom_class_text",
    text        : "Loading"
});
```

But I'd go with a full page overlay, easier and prettier too. What if your user has a 29" monitor? Or a smarphone in landscape mode? Expressing the size in percentage and leaving the positioning up to the plugin always gives the best results in every context.

**Comment by Ofer-Gal** [comment]
I will definitely use your CSS suggestion. Thank you.
As for the whole page overlay, the only reason I use your plugin is it allows the user to choose other views while the current one takes it's time to load. 
When I use whole page overlay, the visible controls, are disabled.

**Comment by gasparesganga** [comment]
Ok then, glad to have helped.
Cheers
