### ISSUE TITLE
On mobile the "back" button shows old Overlay running.

### ISSUE THREAD

**Issue by qroft** [gasparesganga/jquery-loading-overlay#51]
AFAIK this must be a cache problem with the mobile browser, but maybe we together can find a way to solve this.

**SITUATION**
I am on the starting page of my website and when i click for example on the "About me" link to get to that sub-page, i activate a  full screen Overlay. Obviously as soon as the new page (about me) appears, the Overlay is gone as a whole new HTML is loaded.

**PROBLEM**
On my mobile phone: I do the above and once i am on the "About me" page i hit the "back" button of the phone, to get back to the starting page. But as the "old" page is showing, the Overlay still is active.

**WORKAROUND**
First i did a simple timeout of 4 seconds. This means: the new page is loaded and if i hit the back button a couple of seconds later, the overlay is gone. The problem here is that on a slow internet connection, 4 seconds might not be enough. So the Overlay might disappear, thus the user still being on the starting page.

**QUESTION**
Could there be a solution that triggers right before the page is "unloaded". So we could say that "before the new page is loaded, first remove the overlay" ?

Just some idea. I am working with Winter CMS and there are some Init, Right after, Rigth before and Re-Init options via PHP but this looks too heavy for me. The idea here would be to make the PHP Init check if an overlay exists, and if it does, then remove it. but i would prefer to make it with JS or Jquery. 

Any ideas anyone? Greetings from this corner of the planet.

**Comment by gasparesganga** [comment]
Hi!
Just to be 100% sure, are you loading the pages using a pure ajax approach? Since this is a jQuery plugin, it makes sense if all the interactions are actually performed in JS.
I would show the LoadingOverlay, request the next page contents through an ajax call, replace *the contents* of the page (maybe a `<main>` element) and then hiding the LoadingOverlay. You have to be in control of it.
About the back button, you can attach an handler to `window`'s `popstate` event and use JS History API to manipulate it and override default back button behaviour (IE: `history.replaceState("", null, " ");`)

I have never worked with Winter CMS and have no idea about it, so I cannot help you with it, sorry.

**Comment by qroft** [comment]
Your suggestion is totally correct, but I also apparently just found another solution via jQuery by checking the available event listeners of a website and this is what i came up with...

`window.addEventListener( "pageshow", function ( event ) {
    $.LoadingOverlay("hide");
});
`
This means that every time the page is shown, that the overlay is going to be hidden, even if it works in the background.
