### ISSUE TITLE
svg support

### ISSUE THREAD

**Issue by nikklass** [gasparesganga/jquery-loading-overlay#8]
Hi. Thnks for the plugin. Nice work. Does the plugin support svg images? If not, are you planning to add it? SVG is the new standard of clean images, as you may be aware, since it never gets distorted no matter how big it is resized.

**Comment by gasparesganga** [comment]
Hi, you're welcome!
Of course it supports SVG images. You can simply pass it to the [`image` parameter](http://gasparesganga.com/labs/jquery-loading-overlay/#image).

**Comment by nikklass** [comment]
i tried but is not showing image animation. it only shows a static image when i use svg image path

**Comment by gasparesganga** [comment]
Well, this is normal, an SVG image is **_not**_ animated. If you open your SVG image in a browser, do you see any animation?
That's why I chose an animated GIF as default image.
You could try something with CSS3 transformations, or use [FontAwesome](http://gasparesganga.com/labs/jquery-loading-overlay/#fontawesome) which is supported as well by LoadingOverlay, it employs vectorial graphics.

**Comment by gasparesganga** [comment]
Alright, I guess this issue can be closed by now.
